### ISSUE TITLE
library Vte, version 2.91 not available

### ISSUE THREAD

**Issue by raifpy** [amezin/gnome-shell-extension-ddterm#34]
Can't start ddterm - library Vte, version 2.91 not available:
Error: Requiring Vte, version 2.91: Typelib file for namespace 'Vte', version '2.91' not found
![image](https://user-images.githubusercontent.com/50047969/115544363-29d71180-a2ab-11eb-9400-6e8f1cc6025f.png)

GNOME Shell 40.0 OpenSuse Tumbleweed

```
raif@localhost ~> rpm -qa | grep -i vte
libvte-2_91-0-0.63.91-1.1.x86_64
vte-lang-0.63.91-1.1.noarch
libvted-3-0-3.9.0-2.1.x86_64
libvterm0-0.1.3-1.6.x86_64
libvterm-tools-0.1.3-1.6.x86_64
libvterm-devel-0.1.3-1.6.x86_64
```

**Comment by amezin** [comment]
You need to install the package that contains file `Vte-2.19.gir`. Seems that it's a separate package from `libvte` on OpenSuse.

I should improve the error message.

**Comment by raifpy** [comment]
Fixed; https://pkgs.org/download/typelib(Vte)

Thanks...

**Comment by papanito** [comment]
Have the same issue with nixos, not sure what is missing

```
vte
libhandy 
gjs
```

**Comment by amezin** [comment]
Does the nixpkgs package not work for you - https://github.com/NixOS/nixpkgs/blob/a3c1caa738a4d27a91f33b2d5d86c666021e69b2/pkgs/desktops/gnome/extensions/extensionOverrides.nix#L87-L101? If so, you should report the bug there, I think. And, yes, it's also outdated

**Comment by Ffffnord** [comment]
<img width="827" height="637" alt="Image" src="https://github.com/user-attachments/assets/a9ac4c10-2481-4cd9-a325-c1857491ffda" />

Got the same with GNOME OS. I installed Blackbox terminal app, cause it was shown by searching for 'vte', thought it'll catch all this libs but it still won't run.

**Comment by amezin** [comment]
As far as I know, GNOME OS is an immutable distro, and apps are installed as flatpaks only - so if the developers decided not to include Gtk 3 version of Vte in the base image, you can't really do anything about it (other than building Vte from source)

**Comment by Ffffnord** [comment]
Thank you for quick answer, didn't thought it'll be that fast and created a new bug report for this. Sorry.
On the topic: that's sad but I'll try to build it from source then. Any suggestions on how to do this?
I previously stacked with samba sharing and used podman to install in into a container (I'm no familiar with this thing).
But with some instructions from net it somehow works now. Maybe this one will too...

**Comment by Ffffnord** [comment]
I installed it with homebrew and now got the following libs:
alex Jun 22 12:56 ~ > ll /home/linuxbrew/.linuxbrew/lib/ | grep 2.91
lrwxrwxrwx 1 alex alex   45 Jun 22 12:52 libvte-2.91-gtk4.so -> ../Cellar/vte3/0.84.0/lib/libvte-2.91-gtk4.so*
lrwxrwxrwx 1 alex alex   47 Jun 22 12:52 libvte-2.91-gtk4.so.0 -> ../Cellar/vte3/0.84.0/lib/libvte-2.91-gtk4.so.0*
lrwxrwxrwx 1 alex alex   40 Jun 22 12:52 libvte-2.91.so -> ../Cellar/vte3/0.84.0/lib/libvte-2.91.so*
lrwxrwxrwx 1 alex alex   42 Jun 22 12:52 libvte-2.91.so.0 -> ../Cellar/vte3/0.84.0/lib/libvte-2.91.so.0*
lrwxrwxrwx 1 alex alex   49 Jun 22 12:52 libvte-2.91.so.0.8400.0 -> ../Cellar/vte3/0.84.0/lib/libvte-2.91.so.0.8400.0*
alex Jun 22 12:56 ~ > 
How do I link them to ddterm so that can run? Maybe some env prefix?

**Comment by amezin** [comment]
Well in this case you need to install all dependencies (GJS, Gtk 3, Vte, libhandy) from homebrew. Maybe just changing the shebang line in `~/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/bin/com.github.amezin.ddterm` to point to the `gjs` binary from homebrew will be enough, maybe not.

Isn't GNOME OS just a playground for integration testing w/o any stable releases? Why are you using it?

**Comment by Ffffnord** [comment]
Thank you for response! All that deps are installed automatically with brew so I'll try to play with it!

I really like vanilla GNOME! And really do not like RH. Tried to debloat Ubuntu to get one but it became pretty unstable after this. And I'm too lazy for Gentoo. So there's not much of options for me. The GNOME guys got now [stable releases](https://gitlab.gnome.org/GNOME/gnome-build-meta#:~:text=GNOME%20OS%20ISO%20(stable%20Intel%20%26%20AMD)) and it is really stable, got mine running for about a week very smooth and fast, so that is the way the Linux should be, I think. Except few little pita's like this one.
